sap-linuxlab/community.sap_infrastructure

roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/main.yml, roles/sap_hypervisor_node_preconfigure/vars/platform_defaults_redhat_ocp_virt.yml
* updated trident to 23.10 
* renamed variable switch for setting up worker nodes to sap_hypervisor_node_preconfigure_setup_worker_nodes
=> [sap_hypervisor_node_preconfigure] updated trident and fixed variable name

roles/sap_vm_provision/PLATFORM_GUIDANCE.md, roles/sap_vm_provision/tasks/common/set_ansible_vars.yml, roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_provision.yml, roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_setup_ha.yml
PR covers following enhancements:
https://github.com/sap-linuxlab/community.sap_infrastructure/issues/1 
- no_log: "{{ __sap_vm_provision_no_log }}" to hide secrets in -vvv debug mode
- access_key and secret_key were added directly into aws modules because of point above
- region was not added into modules, because Route53 module requires extra parameter interpreter. Region is kept as environment variable.
Additionally covered:
- S-User password assignment in var task is hidden with no_log: true
- Platform guidance was updated with detailed breakdown of IAM Actions as additional option for IAM Policy setup to enhance security.
Rescue block added for failed awscli calls.
=> sap_vm_provision: feat: aws security enhancements

roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/node-network.yml
Support configuring a plain ethernet interface.
=> sap_hypervisor_node_preconfigure: [redhat_ocp_virt] Feature allow setting ethernet devices

roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/main.yml, roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/patch-cluster-masters-unschedulable.yml
The master nodes are set to unschedulable so that no workload ends up running there.
=> sap_hypervisor_node_preconfigure: platform OCPv patch masters unschedulable

roles/sap_vm_provision/PLATFORM_GUIDANCE.md, roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_provision.yml, roles/sap_vm_provision/tasks/platform_ansible/msazure_vm/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible/msazure_vm/execute_provision.yml, roles/sap_vm_provision/tasks/platform_ansible/msazure_vm/execute_setup_ha.yml, roles/sap_vm_provision/tasks/platform_ansible/msazure_vm/post_deployment_execute.yml
Scope:
1. Updated hardcoded `ssh-rsa` to `ssh-` to allow ssh-ed25519 support
2. Added second attempt for IAM Role creation to cover for bug https://github.com/Azure/azure-powershell/issues/4365#issuecomment-351171763 
3. Added retry loop to tasks that are fired too early, like gathering facts on newly built machine.
4. Fixed typos in AZ Load balancer loop vars
5. Updated Azure governance readme with detailed breakdown of Authentication actions, to offer more secure setup compared to privileged Contributor.
6. Added os_register task to Azure for BYOS registration.
7. Fixed loadbalancer STR<>INT  conflicting code
@sean-freeman I am creating this PR now so you are aware of changes, but I will continue with more testing on Azure in coming weeks.
=> sap_vm_provision: Azure compatibility update and fixes

roles/sap_vm_temp_vip/tasks/set_temp_vip.yml
sap_vm_temp_vip: force aws and gcp to use 32 cidr and noprefixroute param
=> sap_vm_temp_vip: force aws and gcp to use 32 cidr and noprefixroute param

roles/sap_vm_provision/defaults/main.yml, roles/sap_vm_provision/tasks/common/set_etc_hosts_scaleout.yml, roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_setup_ha.yml, roles/sap_vm_provision/tasks/platform_ansible/msazure_vm/execute_setup_ha.yml
Description:
1. Introduce new variables for IAM roles to allow parallel clusters in AWS. Same applied for AZ where role was also hardcoded. Solves https://github.com/sap-linuxlab/community.sap_infrastructure/issues/53
```yaml
sap_vm_provision_aws_ha_iam_role: "HA-Role-Pacemaker"
sap_vm_provision_aws_ha_iam_instance_profile: "HA-Instance-Profile-Pacemaker-Cluster"
sap_vm_provision_msazure_ha_iam_role: "Linux Fence Agent Role"
```
2. Update missing IAM permission for fence reboot
3. Update incorrect resource limits on AWS IAM policies from IP to Instance ID. Solves https://github.com/sap-linuxlab/community.sap_infrastructure/issues/53
4. Fix hardcoded hostnames search to regex
- Removed hardcoded reject for all hostnames containing '0'
- Replaced with regex search checking for "ending with …
=> sap_vm_provision: AWS Fencing improvement, Scaleout fix, IAM role changes

roles/sap_vm_provision/defaults/main.yml, roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_setup_ha.yml
Description:
- Add optional variable `sap_vm_provision_aws_dns_overwrite` that can be used to overwrite existing DNS records.
- Default: `false`
- Defaults to `false`, if `sap_vm_provision_aws_dns_overwrite` is not boolean
NOTE: This is required to be set `true` for idempotency, but default handling retains parity between cloud implementations. 
https://docs.ansible.com/ansible/latest/collections/amazon/aws/route53_module.html#parameter-overwrite
=> sap_vm_provision: Add optional AWS DNS overwrite

roles/sap_vm_provision/PLATFORM_GUIDANCE.md, roles/sap_vm_provision/tasks/platform_ansible/gcp_ce_vm/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible/gcp_ce_vm/execute_provision.yml, roles/sap_vm_provision/tasks/platform_ansible/gcp_ce_vm/execute_setup_ha.yml, roles/sap_vm_provision/tasks/platform_ansible/gcp_ce_vm/post_deployment_execute.yml
Description:
- Replaced 90 second pause with wait for ssh connection
- Added fail if resources were not found (OS Image, VPC, VPC Subnet, DNS) and catch it with rescue block
- Enable post provisioning steps which were blocked by incorrect variable name
- Documentation improvements to include detailed breakdown of required permissions and guide for Cloud NAT port blocking issue.
**NOTE**
_Further improvements to HA provisioning might be needed after `sap_ha_pacemaker_cluster` role is reworked due to haproxy._
=> sap_vm_provision: GCP improvements

roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_provision.yml, roles/sap_vm_provision/tasks/platform_ansible/msazure_vm/execute_provision.yml
Added wait_for_connection step for both Azure and AWS. GCP has it already implemented as part of https://github.com/sap-linuxlab/community.sap_infrastructure/pull/54
- AWS was added into same /etc/hosts block as GCP
- Azure requires it sooner so new block was created out of setup module
=> sap_vm_provision: Add wait_for_connection 300 for AWS and AZ

roles/sap_vm_provision/tasks/common/set_ansible_vars.yml
`vars[]` lookup is preventing nested variables from being evaluated.
The loop breaks when a custom `sap_vm_provision_..._host_specifications_dictionary` is used that includes nested variables for flexibility.
All other vars lookups in the role had already been changed to use the lookup plugin some time ago.
Input var:
```
sap_vm_provision_aws_ec2_vs_host_specifications_dictionary:
su_min:
su1hana01: "{{ aws_host_profile.hana_96m_100s.profile_primary }}"
su1hana02: "{{ aws_host_profile.hana_96m_100s.profile_secondary }}"
```
Original syntax and result:
```
- debug:
var: vars['sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_specifications_dictionary'][sap_vm_provision_host_specification_plan][scaleout_origin_host_spec | default('su1hana01')].keys() | map('regex_findall', …
```
=> sap_vm_provision: fix var reference to var lookup

roles/sap_vm_provision/tasks/platform_ansible/gcp_ce_vm/execute_setup_ha.yml
Correction of ASCS variable in ERS block which caused duplicate assignment of frontend under ASCS, while ERS had no frontend rules.
Fixes: Error in ERS NLB
`This load balancer has no frontend configured`
=> sap_vm_provision: GCP typo correction for ERS HA frontend

roles/sap_vm_provision/README.md, roles/sap_vm_provision/tasks/common/register_proxy.yml, roles/sap_vm_provision/tasks/common/set_ansible_vars.yml, roles/sap_vm_provision/tasks/platform_ansible/ibmcloud_powervs/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible/ibmcloud_powervs/execute_provision.yml, roles/sap_vm_provision/tasks/platform_ansible/ibmcloud_vs/execute_provision.yml, roles/sap_vm_provision/tasks/platform_ansible/ibmcloud_vs/execute_setup_ha.yml, roles/sap_vm_provision/tasks/platform_ansible/msazure_vm/execute_setup_ha.yml, roles/sap_vm_temp_vip/tasks/set_temp_vip.yml
sap_vm_provision: exec flow amendments from testing
=> sap_vm_provision: exec flow amendments from testing

roles/sap_vm_provision/tasks/platform_ansible/gcp_ce_vm/execute_main.yml, roles/sap_vm_temp_vip/tasks/set_temp_vip.yml
Added missing enablement of google cloud agent, that allows backend communication between servers using NLB.
Not having this file results in connection blocked.
**NOTE**: This is executed on delegated hosts and it has to be done before NLB creation.
Google servers do not have broadcast IP by default, which is combination missing in VIP role.
Fixes error: `Error: inet address is expected rather than "dev"` caused by empty `primary_ip_broadcast_address`
=> sap_vm_provision/sap_vm_temp_vip: GCP HA improvements and VIP broadcast fix for GCP

roles/sap_vm_temp_vip/INPUT_PARAMETERS.md, roles/sap_vm_temp_vip/README.md, roles/sap_vm_temp_vip/defaults/main.yml, roles/sap_vm_temp_vip/tasks/get_temp_vip_details.yml, roles/sap_vm_temp_vip/tasks/main.yml, roles/sap_vm_temp_vip/tasks/set_temp_vip.yml, roles/sap_vm_temp_vip/tasks/set_temp_vip_lb_listener.yml
- Shell blocks were removed and replaced by Ansible conditional tasks using dynamic variable to reduce copy paste
- Inventory groups were used for selection of variables instead of task conditionals
- New validations before adding IP or starting netcat to improve idempotency
- `lsof` removed and replaced by `ss` which is present on SUSE and Red Hat
- Combine all ip add commands into one IF/ELSE jinja based on broadcast availability
- Make it easier to spot error, because IF/ELSE in shell command is not readable
- Add validations to reduce errors and warnings
All changes were tested on `SUSE Linux Enterprise for SAP 15 SP 5` on:
Platforms:
- AWS
- Google Cloud
- MS Azure
Scenarios:
- SAP ASCS/ERS cluster
- SAP HANA HA cluster
@berndfinger This PR contains new agreed changes in `README.md` …
=> sap_vm_temp_vip: Redesign to replace shell with ansible tasks

playbooks/vars/sample-variables-sap-hypervisor-redhat-ocp-virt-preconfigure.yml
Enabled is not unknown field under interfaces
Currently we get an error :+1: 
$ oc get nncp -A 
NAME                    STATUS      REASON
storagebridge-worker1   Degraded    FailedToConfigure
storagebridge-worker2   Degraded    FailedToConfigure
Events:
Type     Reason           Age   From                     Message
----     ------           ----  ----                     -------
Warning  ReconcileFailed  123m  worker1.nmstate-handler  error reconciling NodeNetworkConfigurationPolicy on node worker1 at desired state apply: "",
failed to execute nmstatectl set --no-commit --timeout 480: 'exit status 1' '' '[2024-11-11T10:12:35Z INFO  nmstatectl] Nmstate version: 2.2.33
Using 'set' is deprecated, use 'apply' instead.
Provide file is not valid NetworkState or NetworkPolicy: interfaces: …
=> Remove enabled: true from storagebridge

playbooks/vars/sample-variables-sap-hypervisor-redhat-ocp-virt-preconfigure.yml, roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/install-cnv-operator.yml
We recently noticed that when a default value is not provided, the system incorrectly defaults to dev-preview. Details are provided in [CNV-51160](https://issues.redhat.com/browse/CNV-51160).
This PR addresses the problem by making it configurable, allowing the appropriate value to be selected.
=> Add subscription channel field 

roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/install-hpp.yml
this label is not needed. We don't require to specify any worker label explictly
=> Remove machineconfig label

roles/sap_vm_provision/defaults/main.yml, roles/sap_vm_provision/tasks/common/register_proxy.yml, roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_provision.yml, roles/sap_vm_provision/tasks/platform_ansible/ibmcloud_powervs/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible/ibmcloud_vs/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible/ibmcloud_vs/execute_provision.yml, roles/sap_vm_provision/tasks/platform_ansible/ibmcloud_vs/execute_setup_ha.yml, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/aws_ec2_vs/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/aws_ec2_vs/tf_template/tf_template_input_vars.tf, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/gcp_ce_vm/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/gcp_ce_vm/tf_template/tf_template_input_vars.tf, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/ibmcloud_powervs/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/ibmcloud_powervs/tf_template/tf_template.tf, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/ibmcloud_powervs/tf_template/tf_template_input_vars.tf, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/ibmcloud_vs/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/ibmcloud_vs/tf_template/tf_template_input_vars.tf, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/ibmpowervm_vm/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/msazure_vm/execute_main.yml, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/msazure_vm/tf_template/tf_template_input_vars.tf, roles/sap_vm_provision/tasks/platform_ansible_to_terraform/vmware_vm/execute_main.yml
sap_vm_provision: os image consistency update and ibmcloud features
=> sap_vm_provision: os image consistency update and ibmcloud features

roles/sap_hypervisor_node_preconfigure/tasks/platform/redhat_ocp_virt/install-cnv-operator.yml
- Introduced retries and checks for the hyperconverged-cluster-webhook pod to ensure it is running before proceeding.
- Added check for the hco-webhook-service to confirm its existence and to avoid webook related errors.
- Improved handling of HyperConverged status by adding checks for resource presence and defined status field.
=> Added checks for HCO webhook components and improve status handling

requirements.yml
Cite logic flaw that disrupts all provision of Azure VM block storage from an Ansible Playbook, and any re-run of Ansible Playbooks:
- https://github.com/ansible-collections/azure/issues/1751
- https://github.com/ansible-collections/azure/issues/1811
=> sap_vm_provision: update ms az req

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/config.yaml
In this commit, the file changelogs/changelog.yml has been manually created from the existing file CHANGELOG.rst and it complies with the standards as published in
https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelogs.md and
https://github.com/ansible-community/antsibull-changelog/blob/main/docs/changelog.yaml-format.md .
The command:
```
antsibull-changelog lint-changelog-yaml changelogs/changelog.yaml
```
returns with return code 0.
The command:
```
antsibull-changelog generate
```
generates the file CHANGELOG.rst from file changelogs/changelog.yaml. The file CHANGELOG.rst is also part of this commit.
Solves #83.
=> collection: Implement file changeslogs/changelog.yaml

requirements.yml
4.6.0 is pretty new, so let's take 4.5.0 for now.
=> collection: Bump vmware.vmware_rest to 4.5.0

roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_setup_ha.yml
Adds tagging for fencing agent `stonith:external/ec2` which has to be same as configured in `sap_ha_pacemaker_cluster` role.
Selected tag name `pacemaker` is present in documentation sources.
SUSE: https://documentation.suse.com/sbp/sap-15/html/SLES4SAP-hana-sr-guide-perfopt-15-aws/index.html#id-tagging-the-ec2-instances
AWS: https://docs.aws.amazon.com/sap/latest/sap-hana/sap-hana-on-aws-stonith-device.html
Tested on SLES4SAP 15 SP6 on ASCS/ERS cluster
```console
TASK [community.sap_infrastructure.sap_vm_provision : AWS EC2 Instances - Ensure pacemaker tag is present] **************************************************
[started TASK: community.sap_infrastructure.sap_vm_provision : AWS EC2 Instances - Ensure pacemaker tag is present on ae1ascs]
ok: [ae1ascs -> localhost] => (item=ae1ascs) …
```
=> sap_vm_provision: AWS tag pacemaker for fence agent stonith:external/ec2

roles/sap_hypervisor_node_preconfigure/README.md, roles/sap_hypervisor_node_preconfigure/vars/platform_defaults_redhat_rhel_kvm.yml
We have initiated Readme overhaul across whole project this year and this PR aligns this repository with it.
- Apply same format to role Readme documents with markdown markers for each section.
This is continuation of https://github.com/sap-linuxlab/community.sap_infrastructure/pull/104
@newkit Make sure to review it locally or in my branch as markdown cannot be reviewed well in github diff view.
- Duplicated variables were removed and pointed towards var file instead.
- We use role variable section in other repositories, but those are formatted differently and they would have to be added here afresh.
=> sap_hypervisor_node_preconfigure: Readme update to align with project readme update

roles/sap_vm_provision/PLATFORM_GUIDANCE.md
- Updated documentation with up-to-date links for VMware as per https://github.com/sap-linuxlab/community.sap_infrastructure/issues/82
=> sap_vm_provision: Append VMware notes for Issue 82

roles/sap_vm_provision/tasks/common/register_os.yml
In register_os.yml: update-ca-certificates does not exist on RHEL and is removed.
https://github.com/sap-linuxlab/community.sap_infrastructure/issues/119
=> sap_vm_provision: Removed update-ca-certificates for issue 119
